music_app/config/routes.rb
MusicApp::Application.routes.draw do
  resources :users do
    collection do
      get 'activate'
    end
  end
  
  resource :session
  
  resources :bands do
    resources :albums, :only => [:index, :new, :create]
  end
  
  resources :albums, :only => [:show, :edit, :update, :destroy] do
    resources :tracks, :only => [:index, :new, :create] 
  end
  
  resources :tracks, :only => [:show, :edit, :update, :destroy] do
    resources :notes, :only => [:new, :create, :destroy]
  end
end

music_app/app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :band_id, :version
  validates :name, :band_id, :version, presence: true
  validates :version, inclusion: { in: %w[live studio]}
  
  belongs_to(
  :band,
  :class_name => "Band",
  :foreign_key => :band_id,
  :primary_key => :id
  )
  
  has_many(
  :tracks,
  :class_name => "Track",
  :foreign_key => :album_id,
  :primary_key => :id,
  :dependent => :destroy
  )
  
end

music_app/app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name
  validates :name, presence: true
  
  has_many(
  :albums,
  :class_name => "Album",
  :foreign_key => :band_id,
  :primary_key => :id,
  :dependent => :destroy
  )
  
  has_many(
  :tracks,
  :through => :albums,
  :source => :tracks,
  :dependent => :destroy
  )
  
end

music_app/app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :user_id, :track_id, :content
  validates :user_id, :track_id, :content, presence: true
  validates :user_id, :track_id, numericality: { only_integer: true }
  
  belongs_to(
  :user,
  :class_name => "User",
  :foreign_key => :user_id,
  :primary_key => :id
  )
  
  belongs_to(
  :track,
  :class_name => "Track",
  :foreign_key => :track_id,
  :primary_key => :id
  )
end

music_app/app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :name, :album_id, :version, :lyrics
  validates :name, :album_id, :version, :lyrics, presence: true
  validates :version, inclusion: { in: %w[regular bonus ]}
  
  belongs_to(
  :album,
  :class_name => "Album",
  :foreign_key => :album_id,
  :primary_key => :id
  )
  
  has_one(
  :band,
  :through => :album,
  :source => :band
  )
  
  has_many(
  :notes,
  :class_name => "Note",
  :foreign_key => :track_id,
  :primary_key => :id
  )
  
  
end

music_app/app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :email, :password_digest, :session_token, :password, :activated, :activation_token
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  before_validation(on: :create) do
    self.reset_session_token! unless self.session_token
    self.set_activation_token! unless self.activation_token
  end
  
  has_many(
  :notes,
  :class_name => "Note",
  :foreign_key => :user_id,
  :primary_key => :id
  )
  
  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end
  
  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
  end
  
  def set_activation_token!
    self.activation_token = SecureRandom.urlsafe_base64(8)
    self.save!
  end
  
  def password=(secret)
    self.password_digest = BCrypt::Password.create(secret)
    self.save!
  end
  
  def is_password?(secret)
    # use BCrypt::Password.new not BCrypt::Password.create
    BCrypt::Password.new(self.password_digest).is_password?(secret)
  end
  
  def self.find_by_credentials(email, secret)
    user = User.find_by_email(email)
    if user
      user if user.is_password?(secret)
    end
  end
end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :require_logged_in!
  
  def index
  end
  
  def show
    @album = Album.find(params[:id])
    render :show
  end
  
  def new
    @bands = Band.all
    render :new
  end
  
  def create
    @album = Album.new(params["album"])
    @album.band_id = params[:band_id]
    
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end
  
  def edit
    @album = Album.find(params[:id])
    render :edit
  end
  
  def update
  end
  
  def destroy
    Album.delete(params[:id])
    # redirect_to 
  end
  
  private
  
  def require_logged_in!
    redirect_to new_session_url unless logged_in?
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  include SessionsHelper
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
  end
  
  def show
    @band = Band.find(params[:id])
    render :show
  end
  
  def new
    render :new
  end
  
  def create
    @band = Band.new(params["band"])
    
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
    Band.delete(params[:id])
  end
end

music_app/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :require_logged_in!
  
  def new
    @track = Track.find(params[:track_id])
    render :new
  end
  
  def create
    note = Note.new(params["note"])
    note.user_id = current_user.id
    track = Track.find(params[:track_id])
    note.track_id = track.id
    
    if note.save
      redirect_to track_url(track)
    else
      flash.now[:errors] = note.errors.full_messages
      render :new
    end
  end
  
  def destroy
    note = Note.find(params[:id])
    Note.delete(note)
    redirect_to track_url(Track.find(params[:track_id]))
  end
  
  private
  
  def require_logged_in!
    redirect_to new_session_url unless logged_in?
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end
  
  def create
    @user = User.find_by_credentials(params["user"]["email"], params["user"]["password"])
    
    if @user
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def destroy
    @user = User.find_by_session_token(session[:session_token])
    logout_user!(@user)
    redirect_to new_session_url
  end
end

music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_filter :require_logged_in!
  
  def index
  end
  
  def show
    @track = Track.find(params[:id])
    render :show
  end
  
  def new
    @albums = Album.all
    render :new
  end
  
  def create
    @track = Track.new(params["track"])
    
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      @albums = Album.all
      # is just rendering the template, :new has access to @track
      render :new
    end
  end
  
  def edit
    @albums = Album.all
    render :edit
  end
  
  def update
  end
  
  def destroy
    Track.delete(params[:id])
  end
  
  private
  
  def require_logged_in!
    redirect_to new_session_url unless logged_in?
  end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :require_logged_in!, except: [:new, :create]
  
  def new
    render :new
  end
  
  def create
    @user = User.new(params["user"])
    
    if @user.save
      login_user!(@user)
      msg = UserMailer.activation_email(@user)
      msg.deliver!
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    render :show
  end
  
  def activate
    @user = User.find_by_activation_token(params["activation_token"])
    if @user
      login_user!(@user)
      @user.activated = true
      @user.save!
      redirect_to user_url(@user)
    end
  end
  
  private
  
  def require_logged_in!
    redirect_to new_session_url unless logged_in?
  end
end

music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/helpers/bands_helper.rb
module BandsHelper
end

music_app/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end
  
  def login_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end
  
  def logged_in?
    !!current_user
  end
  
  def logout_user!(user)
    user.reset_session_token!
    session[:session_token] = nil
  end
end

music_app/app/helpers/tracks_helper.rb
module TracksHelper
end

music_app/app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

music_app/app/helpers/users_helper.rb
module UsersHelper
end

music_app/app/views/albums/_form.html.erb
<%= render :partial => "layouts/errors" %>

<% action_url = (action == :new) ? band_albums_url : edit_album_url(album) %>

<% if action == :new %>
  <h2>Create new album</h2>
<% else %>
  <h2>Edit album</h2>
<% end %>

<form action="<%= action_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
        value="<%= form_authenticity_token %>">
        
<% if action == :edit %>
<input type="hidden" name="_method" value="put">
<% end %> 

<label for="album_band_id">Band</label>
<select name="album[band_id]" id="album_band_id">
  <option></option>
  <% @bands.each do |band| %>
    <option value=<%= band.id %> <%= "selected" if @album && @album.band.id == band.id %>><%= band.name %></option>
  <% end %>
</select>
<br>  
        
<label for="album_name">Album name</label>
<input name="album[name]" id="album_name" type="text">
<br>

<label for="album_version_studio">Studio</label>
<input type="radio" name="album[version]" id="album_version_studio" value="studio" <%= "checked" if @album && @album.version == "studio" %>>
<br>

<label for="album_version_live">Live</label>
<input type="radio" name="album[version]" id="album_version_live" value="live" <%= "checked" if @album && @album.version == "live" %>>
<br>
<br>

<input type="submit" value="Submit">
</form>

music_app/app/views/albums/new.html.erb
<%= render "form", :album => @album, :action => :new %>

music_app/app/views/albums/show.html.erb
<h3>Album</h3>
<%= @album.name %>
<br>

<h3>Band</h3>
<%= link_to("#{@album.band.name}", band_url(@album.band), method: :get) %>
<br>
<br>
<h3>Tracks</h3>
<ul>
<% @album.tracks.each do |track| %>
  <li><%= link_to("#{track.name}", track_url(track), method: :get) %></li>
<% end %>
</ul>
<br>
<%= button_to("Destroy this album!", album_url, method: :delete)%>

music_app/app/views/bands/_form.html.erb
<%= render :partial => "layouts/errors" %>
<% action_url = (action == :new) ? bands_url : edit_band_url(band) %>

<% if action == :new %>
<h2>Create new band</h2>
<% else %>
<h2>Edit band</h2>
<% end %>

<form action="<%= action_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
        value="<%= form_authenticity_token %>">

<% if action == :edit %>
  <input type="hidden" name="_method" value="put">
<% end %>

<label for="band_name">Band name</label>
<input name="band[name]" id="band_name" type="text">
<br>

<input type="submit" value="Submit">
</form>

music_app/app/views/bands/new.html.erb
<%= render "form", :band => @band, :action => :new %>

music_app/app/views/bands/show.html.erb
<h3>Band</h3>
<%= @band.name %>
<br>

<h3>Album</h3>
<ul>
  <% @band.albums.each do |album| %>
  <li><%= link_to("#{album.name}", album_url(album), method: :get) %></li>
  <% end %>
</ul>

<h3>Tracks</h3>
<ul>
<% @band.tracks.each do |track| %>
  <li><%= link_to("#{track.name}", track_url(track), method: :get) %></li>
<% end %>
</ul>

<%= button_to("Destroy this band!", band_url, method: :delete)%>

music_app/app/views/layouts/_errors.html.erb
<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
    <%= error %>
    <br>
  <% end %>
<% end %>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <% if current_user %>
  <%= "Welcome back #{current_user.email}!" %>
  <%= button_to("Log out", session_url, method: :delete) %>
  <% else %>
  <%= button_to("Log in", new_session_url, method: :get) %>
  <%= button_to("Register", new_user_url, method: :get) %>
  <% end %>

<%= yield %>

</body>
</html>

music_app/app/views/notes/_note.html.erb
<%= render :partial => "layouts/errors"%>

<!-- only have new action, no edit at the moment -->
<% action_url = (action == :new) ? track_notes_url : false %>
<h3>Note for <%= @track.name %></h3>
<form action="<%= action_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
        value="<%= form_authenticity_token %>">
        
<label for="note_content">Content</label>
<input name="note[content]" id="note_content" type="text">
<br>
<input type="submit" value="Submit">
</form>

music_app/app/views/notes/new.html.erb
<%= render "note", :action => :new %>

music_app/app/views/tracks/_form.html.erb
<%= render :partial => "layouts/errors" %>
<% action_url = (action == :new) ? album_tracks_url : edit_track_url(track) %>

<% if action == :new %>
<h2>Create new track</h2>
<% else %>
<h2>Edit track</h2>
<% end %>

<form action="<%= action_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
        value="<%= form_authenticity_token %>">

<% if action == :edit %>
  <input type="hidden" name="_method" value="put">
<% end %>

<label for="track_album_id">Album</label>
<select name="track[album_id]" id="track_album_id">
  <option></option>
  <% @albums.each do |album| %>
    <option value=<%= album.id %> <%= "selected" if @track && @track.album.id == album.id %>><%= album.name %></option>
  <% end %>
</select>
<br>  

<label for="track_name">Track name</label>
<input name="track[name]" id="track_name" type="text" value=<%= @track.name if @track %>>
<br>

<label for="track_lyrics">Track lyrics</label>
<textarea name="track[lyrics]" id="track_lyrics" value=<%= @track.lyrics if @track %>>
</textarea>
<br>
<br>

<label for="track_version_regular">Regular</label>
<input type="radio" name="track[version]" id="track_version_regular" value="regular" <%= "checked" if @album && @album.version == "regular" %>>
<br>

<label for="track_version_bonus">Bonus</label>
<input type="radio" name="track[version]" id="track_version_bonus" value="bonus" <%= "checked" if @album && @album.version == "bonus" %>>
<br>
<br>

<input type="submit" value="Submit">
</form>

music_app/app/views/tracks/new.html.erb
<%= render "form", :track => @track, :action => :new %>

music_app/app/views/tracks/show.html.erb
<h3>Track</h3>
<%= @track.name %>
<br>

<h3>Album</h3>
<%= link_to("#{@track.album.name}", album_url(@track.album), method: :get) %>

<h3>Band</h3>
<%= link_to("#{@track.band.name}", band_url(@track.band), method: :get) %>
<br>

<h3>User Notes</h3>
<ul>
<% @track.notes.each do |note| %>
<li><%= note.content %> <%= link_to("Destroy this note!", track_note_url(@track, note), method: :delete) %></li>
<% end %>
</ul>

<!-- have to pass @track because track_id is in the params -->
<%= button_to("Add note", new_track_note_url(@track), method: :get) %>
<%= button_to("Destroy this track!", track_url, method: :delete) %>

music_app/app/views/users/new.html.erb
<%= render :partial => "layouts/errors"%>

<h2>Create new user</h2>

<form action="<%= users_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
        value="<%= form_authenticity_token %>">

<label for="user_email">User email</label>
<input name="user[email]" id="user_email" type="text">
<br>

<label for="user_password">User password</label>
<input name="user[password]" id="user_password" type="text">
<br>
<br>

<input type="submit" value="Submit">
  
</form>

music_app/app/views/users/show.html.erb
<h2>Show page for user</h2>
<label>Email:</label>
<%= @user.email %>